function r = veryfastcorrvec(A,B)
% [r] = fastcorrvec(A,B)
%
% computes a correlation vector r (1xP) between matrices A (NxP) and B (NxP)
% very fast due to MEX build (autogenerated using MATLAB Coder App)
%
% REF: https://en.wikipedia.org/wiki/Pearson_correlation_coefficient
%
% (cc) 2023, dr.seunggoo.kim@gmail.com

N = size(A);
n = N(1);
deA = A - repmat(mean(A,1), [n 1]);
deB = B - repmat(mean(B,1), [n 1]);
r = sum(deA.*deB,1) ./ sqrt(sum(deA.^2,1) .* sum(deB.^2,1));
end